---
title: "Akiyoshi II Participant Weeder"
author: "Nathan Gonzales-Hess"
date: "6/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rio)
library(sjPlot)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
# Load CSV Names
files <-
  list.files(
    path = "data_clean/",
    pattern = ".csv",
    full.names = TRUE,
    recursive = FALSE)

csv_list <- NULL

for (i in 1:length(files)) {
  csv <- read_csv(files[i], show_col_types = FALSE)
  csv_list[[i]] <- csv
}
```

```{r warning=FALSE}
master_df <- bind_rows(csv_list[1:length(csv_list)])
master_df$descriptor <- as.factor(master_df$descriptor)
master_df$speed <- as.factor(master_df$speed)
master_df$beta <- as.factor(master_df$beta)
master_df$fD_f <- as.factor(master_df$fD_f)
master_df$fD_c <- as.numeric(master_df$fD_c)
master_df$ID <- as.factor(master_df$ID)
```

```{r}
comp_df <- NULL
relx_df <- NULL
natr_df <- NULL
intr_df <- NULL
appl_df <- NULL
desc_df <- list(comp_df, relx_df, natr_df, intr_df, appl_df)

descriptors <- c("complex", "relaxing", "natural", "interesting", "appealing")

for (i in 1:5){
  desc_df[[i]] <- master_df[master_df$descriptor == descriptors[i],]
}
```


```{r}
#Grab 'complex' trials only
complex_all <- na.omit(desc_df[[1]])
```

```{r warning=FALSE}
complex_models = NULL
weeder <- NULL
passed <- NULL
ss_df <- data.frame(matrix(nrow=0,ncol = 2))
```

```{r warning=FALSE}
for (i in 1:length(unique(complex_all$ID))){
  current_mdl <- lm(response~fD_c, data = complex_all[complex_all$ID == i,])
  factorial_mdl <- lm(response~fD_f, data = complex_all[complex_all$ID == i,])
  complex_models[i] <- factorial_mdl
  anova <- anova(current_mdl)
  
  # Check if slope is positive and significant
  if (current_mdl$coefficients[2] < 0){
    print(paste("subject", i, "had negative slope"))
    weeder[length(weeder)+1] <- i
  }
  else if (anova$`Pr(>F)` > .05){
    print(paste("subject", i, "had insigificant slope"))
    weeder[length(weeder)+1] <- i
  }
  else{
    passed[length(passed)+1] <- i
  }
  
  ss_df[nrow(ss_df)+1,1] <- i
  ss_df[nrow(ss_df),2] <- sum(anova$`Sum Sq`)
  
}

```
```{r}
# Save passed participants
for (p in 1:length(passed)){
  #Save cleaned CSV
  write.csv(master_df[master_df$ID == passed[p],], file = paste0("data_passed/", passed[p], "_ak3.csv"), row.names = FALSE)
  print(paste("File", passed[p]))
}
```


```{r}
# Build a GGplot function next

for (i in 1:length(weeder)){
plot(complex_models[[weeder[i]]], type="b")
  title(main=paste('Subject',weeder[i]))
plot(x=as.numeric(complex_all[complex_all$ID == weeder[i],]$beta),
     y=complex_all[complex_all$ID == weeder[i],]$response)
title(main=paste('Subject',weeder[i]))
}
```


```{r warning=FALSE, message=FALSE}
# Plot individual participants 

# Grab trials for one descriptor only
desc_all <- na.omit(desc_df[[1]])
# Participant number in list
#i = 33

for (i in 1:length(passed)){
desc_single <- desc_all[desc_all$ID == passed[i],]
agg <- aggregate(desc_single, by=list(desc_single$fD_c), mean)

plt <- ggplot() +
  geom_jitter(aes(x=as.numeric(fD_f), y=response, color=desc_single$speed), width = 0.12, size=1, alpha=.3, data=desc_single) +  
  geom_line(stat="smooth", aes(x=as.numeric(fD_f), y=response, color=desc_single$speed), method = lm, data=desc_single, alpha=.9) +
  #geom_point(aes(y=agg$response, x=c(1:5)), alpha=.5, color="red") +
  #geom_line(aes(y=agg$response, x=c(1:5)), alpha=.5,color="red") +
  scale_x_discrete(limits=c("1.0","1.2","1.4","1.6","1.8")) +
  labs(x="Fractal Dimension", y=paste("Response for", str_to_title(desc_all$descriptor[1]), "Descriptor"),
       title=paste("Subject", passed[i])) +
  ylim(0,100) + theme_classic() + theme(legend.position = "none")

print(plt)
}
```
