---
title: "Akiyoshi II Hierarchical Clustering"
author: "Nathan Gonzales-Hess"
date: "6/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rio)
library(sjPlot)
library(dendextend)
library(data.table)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
# Load CSV Names
files <-
  list.files(
    path = "data_passed/",
    pattern = ".csv",
    full.names = TRUE,
    recursive = FALSE)

agg_data <- data.frame(matrix(ncol = 9, nrow = 0))

descriptor <- 'interesting'
```

```{r}

for (i in 1:length(files)) {
  csv <- read_csv(files[i], show_col_types = FALSE)
  csv <- csv[csv$descriptor == descriptor,]
  
  agg <- aggregate(response~fD_f+descriptor, data=csv, mean, na.rm=T)
  row <- pivot_wider(agg, names_from = c(fD_f, descriptor), values_from = response)
  
  agg_data[i,] <- row
  
}
colnames(agg_data) <- colnames(row)
agg_data$descriptor <- descriptor
```


```{r}
# Set number of clusters
k = 3

# Simple Dendrogram
distance_mat <- dist(agg_data, method = 'euclidean')
set.seed(240)  # Setting seed
hcluster <- hclust(distance_mat, 'ward.D')

# Dendextend Plot - https://cran.r-project.org/web/packages/dendextend/vignettes/Cluster_Analysis.html
dend <- as.dendrogram(hcluster)
# order it the closest we can to the order of the observations:
dend <- rotate(dend, 1:nrow(agg_data))

# Color the branches based on the clusters:
dend <- color_branches(dend, k=k) #, groupLabels=iris_species)
dend <- color_labels(dend, k=k)
# We hang the dendrogram a bit:
dend <- hang.dendrogram(dend,hang_height=0.1)
dend <- dendextend::set(dend, "labels_cex", 0.5)

plot(dend)
```
```{r warning=FALSE}
# Cut Tree and make cluster DF
cut <- cutree(dend, k = k) #== cutree(hc, h = 110))
cut <- as.data.frame(cut)
cut$id <- c(1:nrow(cut))

# Set IDs and Melt
agg_data$id <- row.names(agg_data)
melted <- melt(as.data.table(agg_data))
melted$cluster <- NA
melted$id <- as.numeric(melted$id)
```

```{r}
# Check ID and assign correct cluster -- Check grepl to see if faster
for(i in 1:nrow(melted)){
  for (v in 1:nrow(cut)){
    if(melted[i,2] == v){
      melted$cluster[i] <- cut$cut[v]
      break
      }else{
      melted$cluster[i] <- "fail"
    }
  }
}
```

```{r}
# Get cluster sizes
cluster_n <- as.data.frame(table(cut$cut))

for(i in 1: nrow(cluster_n)){
  print(paste0('Cluster ',cluster_n$Var1[i],': ', round(cluster_n$Freq[i]/sum(cluster_n$Freq)*100,1),'%'))
}
```

```{r}
#plot clusters
cluster_lm <- lm(value~variable*cluster, data=melted)

plt <- plot_model(cluster_lm, type="pred", terms = c("variable", "cluster")) +        
        labs(title = paste0("Comparison of Clusters (\"", ... = str_to_title(agg_data$descriptor[1]), "\" Descriptor)"),
        x = "3d Fractal Beta Value", y = "Participant Response") + geom_line(linetype = "solid", alpha=.5) +
        theme(text = element_text(size=15), plot.title = element_text(hjust = 0.5, margin = margin(t=20, b=20)),
                                             plot.caption = element_text(hjust = 0, face = "italic"),
                                             axis.title.x = element_text(margin = margin(t=30, b=10)),
                                             axis.title.y = element_text(margin = margin(r=30))) +
        #annotate("text", label = cluster_lm$model$cluster, x = 2, y = 15, size = 5, colour = cluster_lm$model$cluster) + 
        theme_minimal()

print(plt) 
```
